### ISSUE TITLE
ASSOCIATION Abstichpunkt_LK* should not be MANDATORY

### ISSUE THREAD

**Issue by sjib** [sia405/rev-modell-pub#1]
Currently all three Associations Abstichpunkt_LKLinieAssoc, LKFlaecheAssoc and LKPunktAssoc are MANDATORY.

```
ASSOCIATION Abstichpunkt_LKLinieAssoc =
      LKLinieRef -<#> {1} LKLinie;
      Abstichpunkt_LKLinieAssocRef -- {0 .. *} Abstichpunkt;
    END Abstichpunkt_LKLinieAssoc;
```
This is wrong as per Abstichpunkt only one Association is MANDATORY and the other will be empty, depending whether it is an Abstichpunkt of LKLinie, LKFlaeche or LKPunkt.

- [ ] New:

```
ASSOCIATION Abstichpunkt_LKLinieAssoc =
      LKLinieRef -<#> {0..1} LKLinie;
      Abstichpunkt_LKLinieAssocRef -- {0 .. *} Abstichpunkt;
    END Abstichpunkt_LKLinieAssoc;
```

- [ ] Adapt also for LKFlaecheAssoc and LKPunktAssoc

- [ ] A new constraint should be added that checks that for each Abstichpunkt exactly one Association LK* is filled in
![20230913_Association_LK_not_MANDATORY](https://github.com/sia405/rev-modell-pub/assets/1265865/26fd15d5-6796-42b4-865f-45a74daa37ee)

**Comment by cymed** [comment]
I am in favour of not creating the new constraint. There are instances where a LKPunkt and an LKLinie can share an Abstichpunkt (i.e. a valve at the end of a water pipe)

**Comment by sjib** [comment]
Do we want an Abstichpunkt to be related to several objects? That could be very complicated in the interpretation mechanism for IFC object. I suggest that in the above case two Abstichpunkte will be generated for LKMap2025, even if in the Erfassungmodell it might be the same.
