### ISSUE TITLE
Domain-Bereich von "Breite" erweitern

### ISSUE THREAD

**Issue by TrThSt** [sia405/rev-modell-pub#10]
https://github.com/sia405/rev-modell-pub/blob/6ba128416afa73ffa10d46e43d9347d1ca1fadd7/ili/SIA405_Base_d_2025_draft.ili#L26

Die Domain Breite anpassen auf 0 .. 9999900
Die Kompatibilität zwischen WI und LK soll gewährleistet sein. Die LK-Breite soll mindestens den Bereich der WI-Modelle abdecken.

**Comment by sjib** [comment]
In der aktuellen SIA405 2015 steht, dass bei Breite > 4000 die Leitung als LKFlaeche abzubilden ist.
