### ISSUE TITLE
Status ohne Projekt

### ISSUE THREAD

**Issue by jag-brm** [sia405/rev-modell-pub#12]
https://github.com/sia405/rev-modell-pub/blob/6ba128416afa73ffa10d46e43d9347d1ca1fadd7/ili/SIA405_Base_d_2025_draft.ili#L86C1-L88C15

Wert Projekt soll gelöscht werden.

**Comment by sjib** [comment]
@jag-brm Das ist in der Vernehmlassung - das kann man nicht schon einfach löschen!
