### ISSUE TITLE
SIA405_Base_d_2025_draft: Plantyp UeP1000

### ISSUE THREAD

**Issue by cymed** [sia405/rev-modell-pub#2]
As Leitungskataster is now defined as 1:200 (good step), a Übersichtsplanposition 1:1000 is missing in SIA405_Base

https://github.com/sia405/rev-modell-pub/blob/6ba128416afa73ffa10d46e43d9347d1ca1fadd7/ili/SIA405_Base_d_2025_draft.ili#L52-L66

 ```
Plantyp = (

      /** Default Leitungskataster 1:200
       */
      Leitungskataster200,
      Uebersichtsplan (
        /** 1:1'000 -- Ergänzung
         */
        UeP1000,
       ...
      ),
     ...    
    );
```

Edit added hyperlink to code

**Comment by cymed** [comment]
@beistehen wurde der Plantyp 1:1000 von der Komission verworfen?

**Comment by beistehen** [comment]
> @beistehen wurde der Plantyp 1:1000 von der Komission verworfen?

Im Gegenteil, er wurde gutgeheissen! Es gibt sogar einen commit dazu, nur wurde dort leider etwas anderes angepasst als dokumentiert. Mein Fehler, sorry. Ist nun definitiv im Modell drin (im öffentlichen Repo noch nicht sichtbar).

Danke für den Hinweis!
