### ISSUE TITLE
Alter Organisationstyp value list

### ISSUE THREAD

**Issue by cymed** [sia405/rev-modell-pub#7]
At 
https://github.com/sia405/rev-modell-pub/blob/6ba128416afa73ffa10d46e43d9347d1ca1fadd7/ili/SIA405_Base_d_2025_draft.ili#L150-L169

The definition of the types "Verband" and "Genossenschaft/Korporation" is is too is narrow . A "selbstständige Interkommunale Anstalt" or a "selbstständige kommunale Anstalt" are neither of the above. 

The underlying logic in the existing disambiguation is separating structures on the community level (Typ Gemeinde and Genossenschaft_Korporation) from structures of inter-communal level (Verband). One solution is:

| old | new |
| ---- | --- |
| `Verband` | `Koerperschaft_oeffentlich_interkommunal` |
| `Genossenschaft_Korporation` | `Koerperschaft_oeffentlich_kommunal` |

**Comment by sjib** [comment]
@cymed 
Vorschlag:
/** interkommunal öffentliche Körperschaft, z.B. Abwasserverband oder Trinkwasserverbund
    */ 
Koerperschaft_oeffentlich_interkommunal,
/** Körperschaft öffentlichen Rechts kommunal, z.B. Genossenschaft oder Korporation. Falls privaten Rechtes dann als Privat abbilden. 
    */ 
   Koerperschaft_oeffentlich_kommunal, 

Hast du noch mehr konkrete Beispiele für die beiden Werte?

**Comment by cymed** [comment]
Ich habe mich noch weiter schlau gemacht: Kirchgemeinden oder Universitäten sind ebenfalls Körperschaften öffentlichen Rechts. Zudem müsste dann eine Lösung für Anstalten des öffentlichen Rechts gefunden werden. Unter Berücksichtigung dieser Punkte ist eine Definition wie

| alt | neu |
| ---- | --- |
| `Verband` | `andere_interkommunale_Organisationsform` |
| `Genossenschaft_Korporation` | `andere_kommunale_Organisationsform` |

zielführender.
Gewisse Kantone erlauben z. B. (inter)kommunale Anstalten , siehe z.B: https://www.wasser2035.ch/ika-definition

**Comment by sjib** [comment]
@cymed - ich verstehe das andere_ nicht. Von was grenzt du dich dann ab?

**Comment by sjib** [comment]
Die Frage für mich dann wieder etwas grundsätzlicher - ob wir da nicht zu tief in die rechtlichen Organisationform hineingehen. Ursprünglich war ja das einfach mal um zu sehen ist es Privat, Gemeinde, Kanton, Verband (und wie jetzt der "Verband" genau organisiert ist, ist mir eigentlich egal  - ich muss mehr die Hierarchiestufen im groben Sinn sehen.

**Comment by sjib** [comment]
@cymed - hier wie telefonisch besprochen die Anpassung der Definitionen statt der Werte.

/** Genossenschaft, Korporation oder andere Form einer Körperschaft des öffentlichen Rechts. Falls privaten Rechtes dann als Privat abbilden. 
    */ 
   Genossenschaft_Korporation, 

/** Verband (z.B. Abwasserverband oder Trinkwasserverbund) oder andere Form einer interkommunalen Organisationform des öffentlichen Rechts
    */ 
   Verband,

**Comment by sjib** [comment]
/** Genossenschaft, Korporation oder andere Form einer **kommunalen** Körperschaft des öffentlichen Rechts. Falls privaten Rechtes dann als Privat abbilden.
*/
Genossenschaft_Korporation,

**Comment by cymed** [comment]
Einheitlich:

/** Genossenschaft, Korporation oder andere Form einer kommunalen **Organisationsform** des öffentlichen Rechts. Falls privaten Rechtes dann als Privat abbilden.
*/
Genossenschaft_Korporation
